### ISSUE TITLE
Link to external resource no longer works.

### ISSUE THREAD

**Issue by PrincetonJRose** [learn-co-curriculum/twitter-follows-readme#1]
Currently the link to  https://www.railstutorial.org/book/following_users  no longer allows users to view the book without making a purchase (only the first 3 chapters are now available to view for free).

**Comment by levimllr** [comment]
There is an older, free version of the book available at https://rails-4-0.railstutorial.org/book/following_users. I suggest replacing the URL on the page with that link.

**Comment by sgharms** [comment]
Looks like this was changed in 86436228. Closing Thanks @levimllr .
